# https://modrinth.com/plugin/unvoidable
# The 'worlds' section allows specifying different configurations for multiple world where the plugin should be active.
worlds:
  # Configuration for 'world1' as an example, you can add as many as you like.
  world1:
    # Coordinates where players will be teleported to if they fall into the void.
    safe-cords: 0.500, 80.000, 0.500
    # Specify yaw and pitch values (e.g., "yaw,pitch"), or set to "false" to disable
    facing: 0.000, 0.000
    # The Y-level is where you want the plugin to consider the void to be located at.
    void-y-level: -64

  # Follows the same patterns.
  world2:
    safe-cords: 0.500, 80.000, 0.500
    facing: 0.000, 0.000
    void-y-level: -64